name: Publish Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Логирование начала процесса

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Log - Installing dependencies
        run: echo "Installing dependencies..."

      - name: Install dependencies
        run: npm install

      - name: Log - Running tests
        run: echo "Running tests..."

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Log - Incrementing patch version
        run: echo "Updating patch version..."

      - name: Increment patch version
        run: npm version patch --no-git-tag-version

      - name: Log - Building the project
        run: echo "Building the project..."

      - name: Build the project
        run: npm run build

      - name: Log - Publishing to npm
        run: echo "Publishing to npm..."

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
