name: Publish Package

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Increment version for temporary publish
        run: |
          TIMESTAMP=$(date +%s)
          npm version patch --no-git-tag-version
          TEMP_VERSION=$(node -p "require('./package.json').version + '-$TIMESTAMP'")
          jq ".version=\"$TEMP_VERSION\"" package.json > tmp.json && mv tmp.json package.json
          echo "Publishing version $TEMP_VERSION"

      - name: Build the project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
