name: Publish Package

on:
  pull_request:
    branches:
      - main
    # Условие, чтобы запускаться только при мёрдже PR
    types: [ closed ]
    paths:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # Логирование начала процесса
        run: echo "Checking out the code..."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
        run: echo "Setting up Node.js..."

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
        # Workflow завершится, если тесты не прошли
        continue-on-error: false

      - name: Increment patch version
        run: |
          echo "Updating patch version..."
          npm version patch --no-git-tag-version

      - name: Build the project
        run: |
          echo "Building the project..."
          npm run build

      - name: Publish to npm
        run: |
          echo "Publishing to npm..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
